name: .NET CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: '**'
    paths:
      - 'src/**'
      - '.editorconfig'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    uses: BugDotNet/.github/.github/workflows/dotnet_ci_build.yml@main
    with:
      configuration: ${{ matrix.configuration }}

  test:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    uses: BugDotNet/.github/.github/workflows/dotnet_ci_test.yml@main
    with:
      configuration: ${{ matrix.configuration }}

  lint:
    uses: BugDotNet/.github/.github/workflows/dotnet_ci_lint.yml@main

  pack:
    uses: BugDotNet/.github/.github/workflows/dotnet_ci_pack.yml@main
